---
title: "Week12"
author: "Ishaan Das"
date: "January 22, 2019"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lattice)
library(dplyr)
library(ggplot2)
library(reshape2)
library(yarrr)
library(stats)
library (NbClust)
library (cluster)
library (clustertend)
library (factoextra)
```

##Kmeans cluster analysis - We will use the IRIS dataset

```{r}
data("iris")
iris2 <- iris[,c(-5)]
iris2 <- scale(iris2)
head(iris2)

#Let us visualize a distance matrix
distance <- get_dist(iris2)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

#Let us also use the USArrests dataset
df <- USArrests
df <- na.omit(df)

#Visualization of a distance matrix
distance <- get_dist(df)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

#Computing Kmeans cluster in R
k2 <- kmeans(df, centers = 2, nstart = 25)
str(k2)

#Let us create a cluster plot
fviz_cluster(k2, data = df)

#We can also increase the number of clusters
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)

# plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)


```